# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailStores',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=50)),
                ('store_abv', models.CharField(max_length=5)),
                ('store_picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
