# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_stores', '0002_auto_20170628_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailstore',
            name='store_picture',
            field=models.ImageField(upload_to='images/retail_stores'),
        ),
    ]
