# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_stores', '0003_auto_20170628_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailstore',
            name='store_picture',
            field=models.ImageField(upload_to='media/images/retail_stores'),
        ),
    ]
